BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBBB BBBBBXXXXXXX gettext(u'title_login') XXXXXXXXBBBBBBBB

BBBBB BBBBBBB
  XXXX XXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      BB BBBBBBBBBBB
          XXX gettext(u'error_login1') XXXX
        BBBBB

        BB BBBB
          BB BBBBBBBBBBBBBBBBBBBBB
            XXX gettext(u'error_login2') XXXX
          BBBB
            XXX gettext(u'error_login3') XXXX
          BBBBB
        BBBBB
        XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBXX
          BBBBBBBBBB
            XXXXXXXXX XXXXXXXXXX
              XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX gettext(u'label_name') XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              XXXXXXXXXXX
              XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX gettext(u'label_pass') XXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              XXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXX gettext(u'login_remember') XXXXXXXXXXXX
            XXXXXXXXXXX
          XXXXXXXX XXXXXXXXX gettext(u'login_forgot') XXXXXXXXXXX
        XXXXXXX
      XXXX XXXXXXXXXXXXXXXXX XXXXXX
    XXXXXX

  XXXXXX
XXXXXX
BBBBBBBB
